version: '3.1'
services:
  prometheus:
    image: xestoso11/prometheus:latest
    container_name: prometheus
    restart: always
    command: 
      # - "--web.config.file=/etc/prometheus/web-config.yml"
      # - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      # - "--web.console.templates=/usr/share/prometheus/consoles"
      # - "--web.external-url=https://localhost:9090/prometheus"
      # - "--storage.tsdb.path=/prometheus"
      # - "--storage.tsdb.retention.time=15d"
      # - "--storage.tsdb.retention.size=1GB"
      # - "--config.file=/etc/prometheus/prometheus.yml"
      - "--config.file.template=/etc/prometheus/prometheus.yml.template"
    environment:
      - ejemplo1=value1
      - ejemplo2=valor2
      - var1=192.168.1.1
      - url_grafana=grafana
      - url_prometheus=prometheus
      - url_alertmanager=alertmanager
      - url_rule_mysql=myslq
    ports:
      - '9090:9090'
    volumes:
      - ./config:/etc/prometheus
      # - ./certs:/etc/prometheus/certs
      - prometheus:/prometheus
volumes:
  prometheus:
